### ISSUE TITLE
Build fails when using typescript with decorators

### ISSUE THREAD

**Issue by alex3683** [alloc/vite-react-jsx#12]
Hi,

we're just evaluating vite with React + TypeScript + MobX (using the decorator syntax). Since I didn't want to use the `esbuild.jsxInject` option and found this plugin, I wanted to use it now :) But alas when doing a build version (not during dev) I get this error:

```
[vite:react-jsx] unknown: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (15:1):

  13 | export interface MainApplicationProps extends AbstractBaseComponentProps {}
  14 |
> 15 | @observer
     | ^
  16 | export default class MainApplication extends AbstractBaseComponent<RootStore, MainApplicationProps> {
  17 |   public render(): JSX.Element {
  18 |     return (
file: C:/projects/app/frontends/applications/setup/src/MainApplication.tsx:15:0
error during build:
SyntaxError: unknown: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (15:1):

  13 | export interface MainApplicationProps extends AbstractBaseComponentProps {}
  14 |
> 15 | @observer
     | ^
  16 | export default class MainApplication extends AbstractBaseComponent<RootStore, MainApplicationProps> {
  17 |   public render(): JSX.Element {
  18 |     return (
    at Object._raise (C:\projects\app\frontends\node_modules\vite-react-jsx\node_modules\@babel\parser\lib\index.js:798:17)
    at Object.raiseWithData (C:\projects\app\frontends\node_modules\vite-react-jsx\node_modules\@babel\parser\lib\index.js:791:17)
    at Object.expectOnePlugin (C:\projects\app\frontends\node_modules\vite-react-jsx\node_modules\@babel\parser\lib\index.js:3272:18)
    at Object.parseDecorator (C:\projects\app\frontends\node_modules\vite-react-jsx\node_modules\@babel\parser\lib\index.js:12978:10)
    at Object.parseDecorators (C:\projects\app\frontends\node_modules\vite-react-jsx\node_modules\@babel\parser\lib\index.js:12960:30)
    at Object.parseStatement (C:\projects\app\frontends\node_modules\vite-react-jsx\node_modules\@babel\parser\lib\index.js:12793:12)
    at Object.parseBlockOrModuleBlockBody (C:\projects\app\frontends\node_modules\vite-react-jsx\node_modules\@babel\parser\lib\index.js:13385:25)
    at Object.parseBlockBody (C:\projects\app\frontends\node_modules\vite-react-jsx\node_modules\@babel\parser\lib\index.js:13376:10)
    at Object.parseProgram (C:\projects\app\frontends\node_modules\vite-react-jsx\node_modules\@babel\parser\lib\index.js:12718:10)
    at Object.parseTopLevel (C:\projects\app\frontends\node_modules\vite-react-jsx\node_modules\@babel\parser\lib\index.js:12709:25)
```

My `tsconfig.json`:
```json
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "composite": true,
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noFallthroughCasesInSwitch": false,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": false,
    "target": "es2015",
  }
}
```

If you need any other information, please let me know.

**Comment by aleclarson** [comment]
Can you try with `@vitejs/plugin-react` and do the following:
```ts
import react from '@vitejs/plugin-react'

export default {
  plugins: [
    react({
      babel: {
        parserOpts: { plugins: ["decorators-legacy"] },
      },
    }),
  ],
};
```

**Comment by alex3683** [comment]
Thanks, that works.

**Comment by aleclarson** [comment]
Note that if/when [#5057](https://github.com/vitejs/vite/pull/5057) is merged, you won't need to add `decorators-legacy` manually anymore (as long as you have `experimentalDecorators: true` in your tsconfig).

**Comment by alex3683** [comment]
Ah, nice. Thanks for the hint!
